# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'stripeBasics' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stripeBasics
pod 'Stripe'
pod 'Alamofire', '~> 4.4'
end
